<a href="https://colab.research.google.com/github/ricaiu/MLPNS2021/blob/main/pyBootParma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My first Notebook

Notebook for learning and exercising on python

In [7]:
dictVariable={'keyInt':0,
              'keyFloat':3.,
              'keyString':'hello',
              'keyDict':{}}

In [8]:
dictVariable

{'keyDict': {}, 'keyFloat': 3.0, 'keyInt': 0, 'keyString': 'hello'}

In [9]:
dictVariable['keyList']=[]

In [10]:
dictVariable

{'keyDict': {},
 'keyFloat': 3.0,
 'keyInt': 0,
 'keyList': [],
 'keyString': 'hello'}

In [11]:
dictVariable['keyDict']['nested']=0.1

In [12]:
dictVariable


{'keyDict': {'nested': 0.1},
 'keyFloat': 3.0,
 'keyInt': 0,
 'keyList': [],
 'keyString': 'hello'}

In [13]:
stringVariable='hello'
stringVariable

'hello'

In [14]:
stringVariable = stringVariable.capitalize()
stringVariable

'Hello'

numpy array are like pointers

In [15]:
import numpy as np

In [29]:
zerosarray = np.zeros(10)
onesarray = np.ones(10)

In [30]:
zerosarray+onesarray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
zerosarray*onesarray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
oneDrandom = np.random.rand(10)
#.randn genera numeri da una distr. gaussiana!

In [41]:
gaussianRandom = np.random.randn(100)

In [42]:
#mylist[::-1] restituisce la lista al contrario

#Esercizio 1

In [96]:
def isApalindrome(a):
  a_nospace = a.replace(' ','')
  b_nospace= a_nospace[::-1]
  if b_nospace.lower() == a_nospace.lower():#so even capital letters work!
    print('Yes!', a, 'is a palindrome')
    print(a_nospace[:int(len(a_nospace)/2+0.5)].lower()) 
  else:
    print('No!', a, 'is NOT a palindrome')

In [97]:
isApalindrome('hello')

No! hello is NOT a palindrome


In [98]:
isApalindrome('ianlnai')


Yes! ianlnai is a palindrome
ianl


In [99]:
isApalindrome('i topi non avevano nipoti')

Yes! i topi non avevano nipoti is a palindrome
itopinonave


In [100]:
isApalindrome('I topi non avevano nipoti')

Yes! I topi non avevano nipoti is a palindrome
itopinonave


In [101]:
from google.colab import drive

In [102]:
drive.mount('/content/drive')

Mounted at /content/drive


In [103]:
from google.colab import drive

In [104]:
ls

drive/  sample_data/


In [105]:
cd drive/

/content/drive


In [106]:
ls

MyDrive/


In [107]:
cd MyDrive/

/content/drive/MyDrive


In [108]:
ls

'041BB_110389 (1).csv.gsheet'
 041BB_110389.csv
 041BB_110389.csv.gsheet
 Acustica/
 Halliday-Fisica11.pdf
 METODI/
 METODI.zip
'Nuovo documento di testo (3).txt'
'[P.Mazzoldi, M.Nigro, C.Voci] Fisica Vol 1 - Meccanica E Termodinamica MNV.pdf'
 progetto-pittorino.gdoc
 progetto-pittorino.pdf
'Silvestrini Mencuccini - Fisica 1.pdf'


In [109]:
ls

'041BB_110389 (1).csv.gsheet'
 041BB_110389.csv
 041BB_110389.csv.gsheet
 Acustica/
 Halliday-Fisica11.pdf
 ispalindrome.py
 METODI/
 METODI.zip
'Nuovo documento di testo (3).txt'
'[P.Mazzoldi, M.Nigro, C.Voci] Fisica Vol 1 - Meccanica E Termodinamica MNV.pdf'
 progetto-pittorino.gdoc
 progetto-pittorino.pdf
'Silvestrini Mencuccini - Fisica 1.pdf'


In [111]:
import ispalindrome as ipl

In [114]:
ipl.lookForPal('anna')

Yes its a palindrome an


1

In [115]:
!curl -O https://raw.githubusercontent.com/fedhere/PyBOOT/master/busBusses.npy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   240  100   240    0     0   3934      0 --:--:-- --:--:-- --:--:--  4000


In [116]:
!curl -O https://raw.githubusercontent.com/fedhere/PyBOOT/master/busTimeTable.npy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1680  100  1680    0     0  22702      0 --:--:-- --:--:-- --:--:-- 22702


In [117]:
ls


'041BB_110389 (1).csv.gsheet'
 041BB_110389.csv
 041BB_110389.csv.gsheet
 Acustica/
 busBusses.npy
 busTimeTable.npy
 Halliday-Fisica11.pdf
 ispalindrome.py
 METODI/
 METODI.zip
'Nuovo documento di testo (3).txt'
'[P.Mazzoldi, M.Nigro, C.Voci] Fisica Vol 1 - Meccanica E Termodinamica MNV.pdf'
 progetto-pittorino.gdoc
 progetto-pittorino.pdf
 __pycache__/
'Silvestrini Mencuccini - Fisica 1.pdf'


In [118]:
tt = np.load('busTimeTable.npy')
busses = np.load('busBusses.npy')

In [119]:
tt


array([[ 91.82869011,  72.99278771,  96.74459251,  73.41298391,
         85.58215726, 101.38226456,  96.97680737,  95.56072596,
         77.87195303,  78.37553397],
       [ 61.03022409,  60.00463334,  67.86228679,  41.10873249,
         53.37659575,  36.91790247,  53.62835897,  55.73660035,
         58.56814116,  54.98889748],
       [ 60.98477297,  45.55742203,  45.88400007,  66.16346096,
         60.03163411,  50.85322708,  45.37677315,  53.8142472 ,
         54.54569551,  60.64418839],
       [ 87.98620643,  55.8021912 ,  81.02751282,  66.19019631,
         53.30000683,  67.55780543,  74.38103569,  71.13924744,
         87.67477883,  67.09783283],
       [ 73.8097995 ,  79.25914025,  86.31085813,  99.77766307,
         90.29078454,  84.37561182,  95.84112464,  84.50840611,
         97.12166748, 105.17515918],
       [ 77.14467806,  71.12444623,  52.12373301,  73.45946947,
         91.36942688,  72.86854378,  68.71403738,  72.43112835,
         61.79702835,  72.26935691],
       [ 8

In [120]:
busses

array([ 77,  72,  79,  97,  85,  57,  86,  96,  31,  76,  33,  98, 109,
       108,  52,  92,  58,  94,  66, 104])

In [129]:
tt.mean(axis=1)

array([ 87.07284964,  54.32223729,  54.38554215,  71.21568138,
        89.64702147,  71.33018484, 101.28441894,  76.05122622,
        73.80479543,  58.25958501,  62.60818564,  83.85318143,
        64.91983233,  38.54594242,  61.47842137,  80.33921739,
        50.13357402,  54.11684661,  70.86680243,  73.45362679])

In [122]:
tt.shape

(20, 10)

In [148]:
hours = np.arange(1,11)

In [149]:
hours

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
timeAvg = tt.mean(axis=1)
busAvg = tt.mean(axis = 0)
print(busAvg.max())
print(timeAvg.max())
index = np.where(timeAvg == timeAvg.max())
print(index[0])
print("il bus che ci mette più tempo", busses[index[0]])

71.58962255653003
101.28441893639999
[6]
il bus che ci mette più tempo [86]


In [152]:
timeAvg == timeAvg.max()
busAvg == busAvg.max()

array([False,  True, False, False, False, False, False, False, False,
       False])

In [153]:
timeAvg[timeAvg == timeAvg.max()]#broadcasting!! trovare l'indice che rispetta una condizione

array([101.28441894])

In [154]:
busAvg[busAvg == busAvg.max()]

array([71.58962256])

In [158]:
hours[busAvg == busAvg.max()] #l'ora con il percorso più lungo in media

array([2])

In [159]:
busses[timeAvg == timeAvg.max()] #il bus che in media ha corre per più tempo

array([86])